overrides:
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  form-data@<2.5.4: '>=2.5.4'
  micromatch@<4.0.8: '>=4.0.8'
  node-sass@>=2.0.0 <7.0.0: '>=7.0.0'
  postcss@<8.4.31: '>=8.4.31'
  scss-tokenizer@<=0.4.2: '>=0.4.3'
  semver@<5.7.2: '>=5.7.2'
  tar@<3.2.2: '>=3.2.2'
  tar@<4.4.18: '>=4.4.18'
  tar@<6.2.1: '>=6.2.1'
  tough-cookie@<4.1.3: '>=4.1.3'
  trim-newlines@<3.0.1: '>=3.0.1'
